# Generated by Django 6.0.1 on 2026-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answerArray',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questionArray',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
