# Generated by Django 6.0.2 on 2026-02-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0003_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
