# Generated by Django 6.0.2 on 2026-02-06 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Logins', '0004_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='questionDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questiontype', models.CharField(max_length=50)),
                ('questionText', models.TextField()),
                ('ispicture', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(blank=True, max_length=255)),
                ('optionC', models.CharField(blank=True, max_length=255)),
                ('optionD', models.CharField(blank=True, max_length=255)),
                ('correctAnswer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='examDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('questionArray', models.JSONField(blank=True, default=list)),
                ('answerArray', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
